const maleProfiles = [
  // {
  //   code: "JM001",
  //   name: "Rahul Shinde",
  //   age: "29",
  //   education: "B.E. Mechanical",
  //   profession: "Engineer",
  //   height: "5'9\"",
  //   location: "Junnar",
  //   family: "Nuclear family",
  //   image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
  //   hobbies: "Reading, Traveling, Cricket",
  //   expectations: "Honest, caring partner with similar values",
  //   fatherOccupation: "Farmer",
  //   motherOccupation: "Housewife",
  //   siblings: "1 brother, 1 sister",
  //   religion: "Hindu",
  //   caste: "Maratha",
  //   dateOfBirth: "1995-05-15",
  //   bloodGroup: "O+",
  //   languages: "Marathi, Hindi, English"
  // },
  // {
  //   code: "JM002",
  //   name: "Amit Dhokale",
  //   age: "31",
  //   education: "MBA",
  //   profession: "Business Owner",
  //   height: "5'10\"",
  //   location: "Narayangaon",
  //   family: "Joint family",
  //   image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
  //   hobbies: "Business, Reading, Gym",
  //   expectations: "Ambitious, family-oriented partner",
  //   fatherOccupation: "Retired Teacher",
  //   motherOccupation: "Housewife",
  //   siblings: "2 sisters",
  //   religion: "Hindu",
  //   caste: "Maratha",
  //   dateOfBirth: "1993-08-22",
  //   bloodGroup: "A+",
  //   languages: "Marathi, Hindi"
  // },
  // {
  //   code: "JM003",
  //   name: "Sagar Jadhav",
  //   age: "28",
  //   education: "B.Com",
  //   profession: "Bank Employee",
  //   height: "5'8\"",
  //   location: "Junnar Taluka",
  //   family: "Educated family",
  //   image: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=600&q=80",
  //   hobbies: "Music, Cooking, Badminton",
  //   expectations: "Kind-hearted, supportive partner",
  //   fatherOccupation: "Government Employee",
  //   motherOccupation: "Teacher",
  //   siblings: "1 brother",
  //   religion: "Hindu",
  //   caste: "Maratha",
  //   dateOfBirth: "1996-12-10",
  //   bloodGroup: "B+",
  //   languages: "Marathi, Hindi, English"
  // }
];

const femaleProfiles = [
   {
    code: "JF11111",
    name: "प्रणाली निवृत्ती भोर",
    age: "28",
    dateOfBirth: "1998-03-20",
    caste: "हिंदू - मराठा",
    ras : "वृश्चिक",
    गण : "राक्षस",
    नाडी : "आद्य",
    देवक : "वासनसड वेल",
    education: "MSc.,B.Ed.",
    profession: "Teacher at मुंबई महानगरपालिका",
    bloodGroup: "A+",
    height: "5'5\"",
    Birthplace: "Manchar",
    Birthtime: "6:15 सकाळी",
    location: "Junnar",
    image: "images/11111_face_1.jpg",
    Fathername:"निवृत्ती जानकू भोर",
    Fatheroccupation:"शेती",
    Mothername:"रंजना निवृत्ती भोर",
    Motheroccupation:"निवृत्त शिक्षिका",
    Siblings:"1 भाऊ (विवाहित), 1 बहीण (विवाहित)",
    Relatives:"कुटे, मोरे, दळवी, मुळीक, पाटे, मुळे, अडसरे, कावडे, थोरात, शिंदे, बांगर",
    expectations: "उच्चशिक्षित, अनुरूप, मुंबईत वास्तव्य",
   
      },
  {
     code: "JF11112",
    name: "अपेक्षा दिलीप डोमसे",
    age: "",
    dateOfBirth: "१८/०७/१९९७",
    caste: "हिंदू मराठा",
    ras: "धनु",
    गण: "राक्षस",
    नाडी: "आद्य",
    देवक: "पाचपाली सौंदड",
    education: "ADIS (Advance Diploma in Industrial Safety),",
    profession: "",
    bloodGroup: "0*",
    height: "५ फूट",
    Birthplace: "",
    Birthtime: "रात्री ९ वा. ४५ मि.",
    location: "कळवा, ता. ठाणे, जि.ठाणे",
    image: "images/11112_face_2.jpg",
    Fathername: "",
    Fatheroccupation: "",
    Mothername: "",
    Motheroccupation: "",
    Siblings: "",
    Relatives: "नलावडे, उर्किडे, भगत, जाधव",
    expectations: "पदवीधर, निर्व्यसनी",

  },
  {
     code: "JF11113",
name: "कु. श्रुती दत्तात्रय डुंबरे",
age: "29",
dateOfBirth: "24/04/1996",
caste: "हिंदू मराठा",
ras: "कर्क",
गण: "राक्षस",
नाडी: "अंत्य",
देवक: "पाचपळी - केळी",
education: "B. E. Information Technology",
profession: "Sr. Associate, JPMorgan Chase & Co (18 LPA)",
bloodGroup: "AB+",
height: "5 फूट 5 इंच",
Birthplace: "ओतूर, जुन्नर",
Birthtime: "सकाळी 6 वा",
location: "कोपरी, ठाणे पूर्व - 400603",
image: "images/11113_face_1.jpg",
Fathername: "श्री. दत्तात्रय सखाराम डुंबरे",
Fatheroccupation: "",
Mothername: "सौ. जयश्री दत्तात्रय डुंबरे",
Motheroccupation: "",
Siblings: "2 बहिणी (विवाहित), 1 भाऊ (विवाहित)",
Relatives: "वालुंज, हांडे, वाघम, शिंगोटे, वाव, सरजिने, घाडगे",
expectations: "समान क्षेत्र, उच्चशिक्षित, नोकरी, निर्व्यसनी"

  },
  {
    code: "JF11114",
    name: "निकिता भगवान पोखरकर",
    age: "29",
    dateOfBirth: "०४/०९/१९९६",
    caste: "हिंदू मराठा",
    ras: "वृषभ",
    गण: "",
    नाडी: "",
    देवक: "",
    education: "BE (Computer Engineering )",
    profession: "software tester",
    bloodGroup: "Atve",
    height: "५.४इंच",
    Birthplace: "",
    Birthtime: "12:05 pm",
    location: "सप्तश्रृंगी बिल्डिंग, दत्तनगर, डोंबिवली(पूर्वी",
    image: "images/11114_face_2.jpg",
    Fathername: "भगवान तुकाराम पोखरकर (मो. नं. - 9029305348)",
    Fatheroccupation: "",
    Mothername: "कांचन भगवान पोखरकर",
    Motheroccupation: "",
    Siblings: "",
    Relatives: "",
    expectations: "Engineer, MBA, CA, Govt. officer,",

  },
   {
code: "JF11116",
name: "कु. श्रद्धा नवनाथ भगत",
age: "25",
dateOfBirth: "22/09/1999",
caste: "हिंदू मराठा",
ras: "कुंभ",
गण: "मनुष्य",
नाडी: "मध्य",
देवक: "पाचपल्लवी सांडस",
education: "Bachelor of Commerce",
profession: "S5 Agency world - Financial Analyst ",
bloodGroup: "B Positive",
height: "5 फूट 4 इंच",
Birthplace: "घाटकोपर (मुंबई)",
Birthtime: "सकाळी 11 वा 20 मि",
location: "घाटकोपर (मुंबई)",
image: "images/11116_face_2.jpg",
Fathername: "श्री नवनाथ गणपत भगत",
Fatheroccupation: "फुलांचे व्यापारी (दादर)",
Mothername: "सौ. रमा नवनाथ भगत",
Motheroccupation: "गृहिणी",
Siblings: "1 बहीण (अविवाहित), 1 भाऊ (अविवाहित)",
Relatives: "भोर, डोंगरे, शिंदे, चव्हाण, गंजाळ, खिलारी, ढोकळे",
expectations: "पदवीधर, मनमिळाऊ, नोकरी करणारी"
  },
   {
    code: "JF11119",
     name: "कु प्रतिक्षा रामदास खंडागळे",
    age: "22",
    dateOfBirth: "22/12/1994",
    caste: "",
    ras: "",
    गण: "",
    नाडी: "",
    देवक: "आरखड",
    education: "",
    profession: "",
    bloodGroup: "",
    height: "",
    Birthplace: "",
    Birthtime: "",
    location: "घाटकोपर (मुंबई - 4000086)",
    image: "images/11119_face_3.jpg",
    Fathername: "श्री रामदास कुंडलिक खंडागळे",
    Fatheroccupation: "फळांचे व्यापारी (कमिशन एजंट)",
    Mothername: "सौ शशिकला रामदास खंडागळे",
    Motheroccupation: "",
    Siblings: "",
    Relatives: "शिंदे, दरेकर, भगत, वाजगे,पोखरकर, चव्हाण",
    expectations: "पदवीधर, नोकरी व व्यवसाय, अनुरूप",

  },
{
   code: "JF11121",
name: "कु. हर्षदा किसन जाधव",
age: "27",
dateOfBirth: "14/07/1998",
caste: "हिंदू- मराठा", 
ras: "कर्क",
गण: "देव",
नाडी: "मध्य",
देवक: "पाचपळी - पानकणीस",
education: "B.E Mechanical",
profession: "कोजेमे इंडिया प्रा. लि चाकण ",
bloodGroup: "AB+VE",
height: "5 फूट",
Birthplace: "वेणगावधाम पारंडे",
Birthtime: "सकाळी 07:55 वाजता",
location: "मु. पो. पारंडे, ता. जुन्नर, जि. पुणे",
image: "images/JF11121-face.jpeg",
Fathername: "श्री. किसन विष्णु जाधव",
Fatheroccupation: "नोकरी - चाकण",
Mothername: "सौ. सुवर्ण किसन जाधव",
Motheroccupation: "गृहिणी",
Siblings: "नाही",
Relatives: "पवार, काशीद, काळे, डेरे, ढोले, फलके, कवडे, थोरात",
expectations: ""
},
{
    code: "JF11122",
    name: "- प्रियांका बाळशिराम पिंगळे",
    age: "",
    dateOfBirth: "- ११/०५/१९९४",
    caste: "- हिंदू - मराठा",
    ras: "- मेष",
    गण: "- राक्षस",
    नाडी: "- अंत्य",
    देवक: "- पाचपाली सौंदड",
    education: "- बी.कॉम. सी. ए. फायनल",
    profession: "- नोकरी गोदरेज कंपनी विक्रोळी",
    bloodGroup: "- AB पॉझिटिव्ह",
    height: "- ५ फूट १ इंच",
    Birthplace: "",
    Birthtime: "- सकाळी ६ AT, ०५ मि.",
    location: "- X-96/4 गोदरेज स्टेशन कॉलनी",
    image: "images/JF11122 -face.jpeg",
    Fathername: "",
    Fatheroccupation: "- नोकरी गोदरेज कंपनी विक्रोळी",
    Mothername: "- सौ. सिंधू बाळशिराम पिंगळे",
    Motheroccupation: "",
    Siblings: "",
    Relatives: "- मटाले, हुले, ANA, वायकर,नायकोडी, कदम",
    expectations: "",
},
// {
// code: "JF11123",
// name: "रोहिणी (मोनू) प्रदिप फलके",
// age: "27",
// dateOfBirth: "15 डिसेंबर 1998",
// caste: "हिंदू - 96 कुळी मराठा",
// ras: "तुळ",
// गण: "देव",
// नाडी: "अंत्य",
// देवक: "पाचपाळी सोंदड",
// education: "B.Sc. Physics",
// profession: "KPO Officer, Atos Syntel, Talawade",
// bloodGroup: "A+",
// height: "5 फूट 5 इंच",
// Birthplace: "घोडेगाव, ता. आंबेगाव",
// Birthtime: "सायंकाळी 7:20",
// location: "विकास कॉलनी, भोसरी / मु. आंढी, घोडेगाव, ता. आंबेगाव, जि. पुणे",
// image: "JF11123.jpeg",
// Fathername: "प्रदिप बबन फलके",
// Fatheroccupation: "शेती",
// Mothername: "उर्मिला प्रदिप फलके",
// Motheroccupation: "",
// Siblings: "1 भाऊ (अविवाहित)",
// Relatives: "राजगुरु, कोकणे, तांबे, पाचपुते, तोतरे, निघुट, शेटे, गव्हाणे",
// expectations: ""
// },
// {
//   code: "JF11124",
// name: "RESHMA SHIVAJI BHOR",
// age: "40",
// dateOfBirth: "08/11/1984",
// caste: "",
// ras: "MESH",
// गण: "DEVGAN",
// नाडी: "AADYA",
// देवक: "VASANSADI PACHHPAL",
// education: "T.Y.B.A",
// profession: "SELF EMPLOYED, TUITION INCOME",
// bloodGroup: "O+",
// height: "5'3\"",
// weight:"",
// Birthplace: "NARAYAN GAON",
// Birthtime: "12.30 AM",
// location: "GOREGAON (W), MUMBAI 400062",
// image: "JF11124.jpeg",
// Fathername: "SHIVAJI NATHA BHOR",
// Fatheroccupation: "AUTO DRIVER",
// Mothername: "SHARDA SHIVAJI BHOR",
// Motheroccupation: "",
// Siblings: "",
// Relatives: "PATE, GHANGLE, GHULE, BHALERAO, DANGAT, THORAT, KALE",
// expectations: ""
// },
// {
//   code: "JF11125",
// name: "निकिता विष्णू सूर्यवंशी",
// age: "२६",
// dateOfBirth: "२५/१०/१९९९",
// caste: "हिंदू - धनगर",
// ras: "",
// गण: "",
// नाडी: "",
// देवक: "",
// education: "B.Com, MBA(HR)",
// profession: "HR cum Accountant",
// bloodGroup: "O+",
// height: "५.४",
// Birthplace: "भोसरी पुणे",
// Birthtime: "",
// location: "मोहननगर चिंचवड पुणे",
// image: "JF11125.jpeg",
// Fathername: "कै. विष्णू गणपत सूर्यवंशी",
// Fatheroccupation: "",
// Mothername: "श्रीमती संगीता विष्णू सूर्यवंशी",
// Motheroccupation: "गृहिणी",
// Siblings: "२ बहिणी (विवाहित)",
// Relatives: "",
// expectations: "पदवीधर, समजूतदार, परस्पर आदर व विश्वास ठेवणारा, सुसंस्कृत व कुटुंबवत्सल"
// },
{
  code: "JF11126",
name: "स्नेहल शिवाजी रकळे",
age: "",
dateOfBirth: "१ ऑक्टोबर १९९६",
caste: "हिंदू - मराठा",
ras: "",
गण: "",
नाडी: "",
देवक: "पाचपळी-सोंडड",
education: "Bachelor of Computer Science (BCS), MBA Finance",
profession: "Apex co. Pune (5.20 lakh PA)",
bloodGroup: "B+ve",
height: "५ फूट ३ इंच",
Birthplace: "आळेफाटा",
Birthtime: "संध्याकाळी ०८ वाजता",
location: "MIDC शाहूनगर, चिंचवड, पुणे",
image: "images/JF11126 -face.jpeg",
Fathername: "श्री. शिवाजी राजाराम रकळे",
Fatheroccupation: "TATA MOTORS",
Mothername: "सौ. संगीता शिवाजी रकळे",
Motheroccupation: "",
Siblings: "१ बहीण (विवाहित), १ भाऊ (अविवाहित)",
Relatives: "ढमाले, थिटे, वाघ, फाफळे, तांबे, डुंबरे",
expectations: ""
},
// {
//    code: "JF11127",
// name: "कु. डॉ. श्वेता सयाजीराव चिखले",
// age: "",
// dateOfBirth: "१३/०४/१९९७",
// caste: "हिंदू - मराठा",
// ras: "मिथुन",
// गण: "मनुष्यगण",
// नाडी: "",
// देवक: "कळंबाच",
// education: "BDS Pune, Certified Endodontist Bangalore",
// profession: "स्वतःचे क्लिनिक (श्री स्वामी समर्थ डेंटल क्लिनिक, खोदड रोड, नारायणगाव)",
// bloodGroup: "B+",
// height: "५ फूट ५ इंच",
// Birthplace: "मांजरवाडी, ता. जुन्नर, जि. पुणे",
// Birthtime: "रात्री ११:३०",
// location: "वारूळवाडी, ना.गाव, ता. जुन्नर, जि. पुणे",
// image: "JF11127.jpeg",
// Fathername: "श्री. सयाजीराव दत्तात्रय चिखले",
// Fatheroccupation: "प्राथमिक शिक्षक",
// Mothername: "सौ. सुमन सयाजीराव चिखले",
// Motheroccupation: "प्राथमिक शिक्षक",
// Siblings: "२ बहिणी (१ विवाहित, १ अविवाहित)",
// Relatives: "म्हस्के, चव्हाण, कराळे, थोरात, नलावडे, पटोळे, ओटी, गोडसे, गुंजाळ, फाफळे, खंडागळे, कुंडले, हाडवळे",
// expectations: "MBBS / MD / IT Engg / BDS / MDS / BAMS, स्वतःचे क्लिनिक, हॉस्पिटल"
// },
// {
// code: "JF11128",
// name: "कु. प्रांजली प्रकाश बेंके",
// age: "",
// dateOfBirth: "04/08/1996",
// caste: "हिंदू - मराठा",
// ras: "",
// गण: "देवगण",
// नाडी: "अंत्य",
// देवक: "वासरांजळी बेल",
// education: "B.E. (Mech.), Mechanical Design Course",
// profession: "Valmet Pune",
// bloodGroup: "O+",
// height: "5 फूट 2 इंच",
// Birthplace: "राजुरी, ता. जुन्नर, जि. पुणे",
// Birthtime: "सकाळी 9:45",
// location: "हिवरे बु., ता. जुन्नर, जि. पुणे",
// image: "JF11128.jpeg",
// Fathername: "श्री. प्रकाश नथु बेंके",
// Fatheroccupation: "अजंठा साखर कारखाना, जुन्नर/आंबेगाव",
// Mothername: "सौ. नलिनी प्रकाश बेंके",
// Motheroccupation: "",
// Siblings: "1 भाऊ (नोकरी)",
// Relatives: "नायकोडी, बो-होळे, हाडवळे, शिंदे, पखळे, कु-होळे, भटकळ, काळे, चिखले",
// expectations: ""
// },
// {
//    code: "JF11129",
// name: "कु. पूजा गोविंद बेंके",
// age: "39",
// dateOfBirth: "12 मार्च 1987",
// caste: "हिंदू - मराठा",
// ras: "कर्क",
// गण: "देव",
// नाडी: "मध्य",
// देवक: "वासरांडा",
// education: "Postgraduate Diploma in Human Resource Management (PGDHRM), Welingkar Institute",
// profession: "आदित्य बिर्ला ग्रुप (11 लाख वार्षिक)",
// bloodGroup: "O+",
// height: "5 फूट 5 इंच",
// Birthplace: "मुंबई (कांदिवली)",
// Birthtime: "पहाटे 5:09",
// location: "पुनम दीपक कोलेकर, ग्रीन टॉवर फेज 2, वाघबिल रोड, ऑफ घोडबंदर रोड, ठाणे (पश्चिम) - 400615",
// image: "JF11129.jpeg",
// Fathername: "श्री. गोविंद गणपत बेंके",
// Fatheroccupation: "",
// Mothername: "कै. कमल गोविंद बेंके",
// Motheroccupation: "",
// Siblings: "",
// Relatives: "हांडे, कोलेकर, धांगळे, सेद, डंगे, डोंगरे, बो-होळे",
// expectations: ""
// },
// {
//    code: "JF11130",
// name: "कु. पृथ्वी भानुदास भोर",
// age: "",
// dateOfBirth: "16/12/1996",
// caste: "हिंदू - मराठा",
// ras: "मिथुन",
// गण: "मध्य",
// नाडी: "आद्य",
// देवक: "वासरांडा",
// education: "M.Com (Banking and Finance)",
// profession: "Link Group, Vikhroli West",
// bloodGroup: "A+",
// height: "5 फूट",
// Birthplace: "नारायणगाव, पुणे",
// Birthtime: "सकाळी 10:55",
// location: "विक्रोळी (पूर्व), मुंबई",
// image: "JF11130.jpeg",
// Fathername: "श्री. भानुदास शिवाजी भोर",
// Fatheroccupation: "गोदरेज & बॉईस कंपनी प्रा. लि., विक्रोळी (पूर्व), मुंबई",
// Mothername: "सौ. जयश्री भानुदास भोर",
// Motheroccupation: "गृहिणी",
// Siblings: "१ बहीण (विवाहित), १ भाऊ (अविवाहित)",
// Relatives: "काळे, लोखंडे, सुकळे, बोडके, होले, वांजुळे, काशीद, दुगुंडे, सेंदे, गाडे",
// expectations: ""
// },
// {
// code: "JF11131",
// name: "कु. संचित्ता कचरू हुळे",
// age: "27",
// dateOfBirth: "21/09/1998",
// caste: "हिंदू - मराठा (96 कुळी)",
// ras: "कन्या",
// गण: "मनुष्य",
// नाडी: "आद्य",
// देवक: "पाचपाळी (सोंडड)",
// education: "MBA in Financial Management",
// profession: "Associate Consultant at EY (Ernst & Young) (8-10 LPA)",
// bloodGroup: "O+",
// height: "5 फूट 3 इंच",
// Birthplace: "चारस (नारोडी), ता. आंबेगाव, जि. पुणे",
// Birthtime: "पहाटे 1:00",
// location: "दिवा, एरोली, नवी मुंबई / नारोडी, ता. आंबेगाव, जि. पुणे",
// image: "JF11131.jpeg",
// Fathername: "श्री. कचरू हरिश्चंद्र हुळे",
// Fatheroccupation: "B.Com (नोकरी)",
// Mothername: "सौ. सुजाता कचरू हुळे",
// Motheroccupation: "B.A. (नोकरी)",
// Siblings: "1 भाऊ (Studying BE in IT)",
// Relatives: "भोर, थोरात, माशेरे, देने, निघोट, हांडे, चासकर, बाणखेले, जाधव",
// expectations: "सुशिक्षित, सुसंस्कृत"
// },
// {
//     code: "JF11132",
//     name: "",
//     age: "",
//     dateOfBirth: "",
//     caste: "",
//     ras: "",
//     गण: "",
//     नाडी: "",
//     देवक: "",
//     education: "",
//     profession: "",
//     bloodGroup: "",
//     height: "",
//     Birthplace: "",
//     Birthtime: "",
//     location: "",
//     image: "JF11132.jpeg",
//     Fathername: "",
//     Fatheroccupation: "",
//     Mothername: "",
//     Motheroccupation: "",
//     Siblings: "",
//     Relatives: "",
//     expectations: "",
// },
// {
//    code: "JF11133",
// name: "कु. संचित्ता कचरू हुळे",
// age: "27",
// dateOfBirth: "21/09/1998",
// caste: "हिंदू - मराठा (96 कुळी)",
// ras: "कन्या",
// गण: "मनुष्य",
// नाडी: "आद्य",
// देवक: "पाचपाळी (सोंडड)",
// education: "MBA in Financial Management",
// profession: "Associate Consultant at EY (Ernst & Young) (8-10 LPA)",
// bloodGroup: "O+",
// height: "5 फूट 3 इंच",
// Birthplace: "चारस (नारोडी), ता. आंबेगाव, जि. पुणे",
// Birthtime: "पहाटे 1:00",
// location: "दिवा, एरोली, नवी मुंबई / नारोडी, ता. आंबेगाव, जि. पुणे",
// image: "JF11131.jpeg",
// Fathername: "श्री. कचरू हरिश्चंद्र हुळे",
// Fatheroccupation: "B.Com (नोकरी)",
// Mothername: "सौ. सुजाता कचरू हुळे",
// Motheroccupation: "B.A. (नोकरी)",
// Siblings: "1 भाऊ (Studying BE in IT)",
// Relatives: "भोर, थोरात, माशेरे, देने, निघोट, हांडे, चासकर, बाणखेले, जाधव",
// expectations: "सुशिक्षित, सुसंस्कृत"
// },
// {
//    code: "JF11134",
// name: "श्वेताली सुरेश कोटदे",
// age: "26",
// dateOfBirth: "19 नोव्हेंबर 1999",
// caste: "हिंदू मराठा",
// ras: "मीन",
// गण: "मनुष्य",
// नाडी: "मध्य",
// देवक: "दुधफुल",
// education: "Mcom (Accounting and Finance)",
// profession: "Accenture",
// bloodGroup: "A+",
// height: "5 फूट 1 इंच",
// Birthplace: "राजगुरूनगर खेड",
// Birthtime: "11.30 AM",
// location: "वाशी नवी मुंबई / राजगुरूनगर खेड, जि. पुणे",
// image: "42c19430-2c91-4436-bd87-40e36b67aaf7.jpeg",
// Fathername: "सुरेश सहादु कोटदे",
// Fatheroccupation: "",
// Mothername: "मंगला सुरेश कोटदे",
// Motheroccupation: "",
// Siblings: "1 भाऊ अविवाहित - तेजस सुरेश कोटदे",
// Relatives: "पवार, थिटे, भांबुरे, नातपुते, पवळे",
// expectations: "निर्व्यसनी, सुशिक्षित"
// },
{
 code: "JF11135",
name: "उत्कर्षा कैलास शिंदे",
age: "28",
dateOfBirth: "12/12/1997",
caste: "हिंदू मराठा",
ras: "मीन",
गण: "देव",
नाडी: "अंत्य",
देवक: "मरिचाचे कडे",
education: "एम कॉम, चार्टर्ड अकाउंटन्सी, सी ए फायनल, सेकंड ग्रुप क्लिअर",
profession: "आर व्ही टी एंड असोसिएट्स",
bloodGroup: "O+ve",
height: "5 फूट 3 इंच",
Birthplace: "नारायणगाव (पुणे)",
Birthtime: "दुपारी 2:20",
location: "भिमाशंकर सो., सेक्टर-29, नेरूळ, नवी मुंबई / बोरी बु., ता. जुन्नर, जि. पुणे",
image: "images/JF11135 -face.jpeg",
Fathername: "श्री. कैलास भगवत शिंदे",
Fatheroccupation: "नोकरी - बी. एम. सी (BMC)",
Mothername: "सौ. सुजाता कैलास शिंदे",
Motheroccupation: "गृहिणी",
Siblings: "1 भाऊ - भानुद कैलास शिंदे (अविवाहित) - BSc C.S",
Relatives: "आतकरी, बाणखेले, कोकणे, कोरडे, डेरे",
expectations: "उच्चशिक्षित, समजूतदार, प्रगतीशील विचार, नोकरी (CA/CS/इंजिनिअर/कायानल/एम.बी.ए)"
},
{
  code: "JF11136",
name: "पूजा काळुराम कोतवाल",
age: "31",
dateOfBirth: "26 एप्रिल 1994",
caste: "",
ras: "तुळ",
गण: "राक्षस",
नाडी: "अंत्य",
देवक: "पाचपाळी दवणा",
education: "Chemical engineer",
profession: "",
bloodGroup: "O+",
height: "5 फूट 3 इंच",
Birthplace: "राजगुरूनगर, खेड",
Birthtime: "दुपारी 03 वा. 20 मि.",
location: "राजगुरूनगर, माळी मळा, वृंदावन सोसायटी, पुणे-410505 / मु. पो. भांबवाडी, तालुका-खेड, जिला-पुणे",
image: "images/JF11136 -face.jpeg",
Fathername: "काळुराम भागाजी कोतवाल",
Fatheroccupation: "Ministry of Defence",
Mothername: "सौ. संगीता काळुराम कोतवाल",
Motheroccupation: "",
Siblings: "1 भाऊ - श्री. अमर काळुराम कोतवाल (MCA)",
Relatives: "मुळूक, पालेकर, भोजगडे, बोराडे, पवार, होरे, जरे, तोडकरी, बुढे, करंजखेडे",
expectations: ""},
{
   code: "JF11137",
name: "कु. अश्विनी सुधाकर सेंद",
age: "28",
dateOfBirth: "23/12/1997",
caste: "हिंदू मराठा",
ras: "कन्या",
गण: "राक्षस",
नाडी: "मध्य",
देवक: "पाचपाळी, पानकणिस",
education: "एम एस सी, ऑर्गॅनिक केमेस्ट्री",
profession: "विल्सर सिंथ लॅब, हैद्राबाद",
bloodGroup: "O+",
height: "5.3",
Birthplace: "वासुंदे, ता. पारनेर",
Birthtime: "2:40",
location: "मुंडळ, कळवण / राजुरी",
image: "images/JF11137-face.jpeg",
Fathername: "सुधाकर बाळू सेंद",
Fatheroccupation: "",
Mothername: "सौ. ज्योती सुधाकर सेंद",
Motheroccupation: "",
Siblings: "1 भाऊ - श्री. स्वप्निल सुधाकर सेंद",
Relatives: "शिर्के, टेमकर, शिंदे, साळुंके, शेळके, काणे, भोर, मोरे, कोल्हे, जाधव",
expectations: ""
}
,{
  code: "JF11139",
  name: "अक्षरा योगेश घुले",
  age: "30",
  dateOfBirth: "04/10/1995",
  caste: "हिंदू मराठा",
  ras: "मकर",
  गण: "देव",
  नाडी: "अंत्य",
  देवक: "",
  education: "BE (IT)",
  profession: "Clarion Tech, Pune",
  bloodGroup: "A+",
  height: "5 फूट 4 इंच",
  Birthplace: "नाशिक",
  Birthtime: "सकाळी 06:29",
  location: "नाशिक",
  image: "images/JF11139 -face.jpeg",
  Fathername: "श्री. योगेश खंडेराव घुले",
  Fatheroccupation: "",
  Mothername: "सौ. संगीता योगेश घुले",
  Motheroccupation: "",
  Siblings: "2 (विवाहित)",
  Relatives: "वाकळे, मोरे, आढाव",
  expectations: "BE, ME, MCA, BCA, BPharm"
},

{
  code: "JF11140",
  name: "सुचिता संजीव निकम",
  age: "30",
  dateOfBirth: "02/04/1996",
  caste: "हिंदू मराठा",
  ras: "मकर",
  गण: "राक्षस",
  नाडी: "मध्य",
  देवक: "काकत",
  education: "M.Com",
  profession: "",
  bloodGroup: "A+ve",
  height: "4 फूट 10 इंच",
  Birthplace: "घाटकोपर (मुंबई)",
  Birthtime: "पहाटे 04:25",
  location: "ता. कोरेगाव, जि. सातारा",
  image: "images/JF11140-face.jpeg",
  Fathername: "श्री. संजीव वसंत निकम",
  Fatheroccupation: "",
  Mothername: "श्रीमती सुनीता संजीव निकम",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "",
  expectations: ""
},


{
  code: "JF11141",
  name: "सोनल सुरेश फडके",
  age: "30",
  dateOfBirth: "20/02/1996",
  caste: "हिंदू मराठा",
  ras: "कुंभ",
  गण: "मनुष्य",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "BBI",
  profession: "Commercial Assistant (Hindustan Field Service)",
  bloodGroup: "B+",
  height: "5 फूट 4 इंच",
  Birthplace: "ठाणे",
  Birthtime: "दुपारी 12:00",
  location: "ठाणे / पुणे",
  image: "images/JF11141-face.jpeg",
  Fathername: "के. सुरेश बबन फडके",
  Fatheroccupation: "",
  Mothername: "श्रीमती उषा सुरेश फडके",
  Motheroccupation: "",
  Siblings: "1 बहिण (विवाहित)",
  Relatives: "राजपूत, कामटे, येवले",
  expectations: ""
},

{
  code: "JF11142",
  name: "रोहिणी प्रदीप फडके",
  age: "27",
  dateOfBirth: "15/12/1998",
  caste: "हिंदू मराठा",
  ras: "तुळ",
  गण: "देव",
  नाडी: "अंत्य",
  देवक: "पाचपळी",
  education: "B.Sc Physics",
  profession: "KPO Officer, Atos Syntel",
  bloodGroup: "A+",
  height: "5 फूट 5 इंच",
  Birthplace: "घोडगाव",
  Birthtime: "संध्याकाळी 07:20",
  location: "पुणे",
  image: "images/JF11142 -face.jpeg",
  Fathername: "प्रदीप बबन फडके",
  Fatheroccupation: "शेती",
  Mothername: "जमिला प्रदीप फडके",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "राजपूत, कोकणे, तांबे",
  expectations: ""
},

{
  code: "JF11143",
  name: "मयुरी बाबू थोरावे",
  age: "25",
  dateOfBirth: "02/12/2000",
  caste: "हिंदू मराठा",
  ras: "मीन",
  गण: "मनुष्य",
  नाडी: "मध्य",
  देवक: "पाचपळी",
  education: "B.Com / MBA",
  profession: "IndusInd Bank",
  bloodGroup: "A+",
  height: "5 फूट 3 इंच",
  Birthplace: "",
  Birthtime: "",
  location: "जुन्नर, पुणे",
  image: "images/JF11143-face.jpeg",
  Fathername: "श्री. बाबू एकनाथ थोरावे",
  Fatheroccupation: "",
  Mothername: "सौ. सविता बाबू थोरावे",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "बोचरे, जेधे, नखाते",
  expectations: ""
},

{
  code: "JF11144",
  name: "सुकन्या कैलास गोरडे",
  age: "27",
  dateOfBirth: "08/07/1999",
  caste: "हिंदू मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "",
  education: "B.E (IT)",
  profession: "LTI-Mindtree, Pune (Package: 12 LPA)",
  bloodGroup: "B+",
  height: "5 फूट 5 इंच",
  Birthplace: "नाशिक",
  Birthtime: "दुपारी 03:13",
  location: "पुणे",
  image: "images/JF11144 -face.jpeg",
  Fathername: "श्री. कैलास मारुती गोरडे",
  Fatheroccupation: "",
  Mothername: "सौ. संगीता कैलास गोरडे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "थोरात, जाधव, पाटील",
  expectations: "Software engineer, Pune job preferred"
}
,

{
  code: "JF11145",
  name: "निकिता अर्जुन वाकडे",
  age: "29",
  dateOfBirth: "03/12/1996",
  caste: "हिंदू - मराठा",
  ras: "वृश्चिक",
  गण: "मनुष्य",
  नाडी: "अंत्य",
  देवक: "पाचपळी - फणस",
  education: "B.E. Computer Engineer",
  profession: "Cencora, Yeravada, Pune",
  bloodGroup: "O+ve",
  height: "5 फूट 5 इंच",
  Birthplace: "गांगापुर",
  Birthtime: "रात्री 9:30",
  location: "मू.पो. खडकी, ता. आंबेगाव, जि. पुणे",
  image: "images/JF11145-face.jpeg",
  Fathername: "श्री. अर्जुन वर्कीस वाकडे",
  Fatheroccupation: "शेती",
  Mothername: "सौ. लक्ष्मी अर्जुन वाकडे",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ - शुभम अर्जुन वाकडे (अविवाहित)",
  Relatives: "शिंदे, मनकर, देशमुख, पवार, ठोसर, बांगर, पोंधळकर",
  expectations: ""
},{
  code: "JF11146",
  name: "भाग्यश्री अशोक नेतेवकर",
  age: "26",
  dateOfBirth: "23/08/1999",
  caste: "हिंदू - मराठा",
  ras: "धनु",
  गण: "राक्षस",
  नाडी: "मध्य",
  देवक: "कवड",
  education: "BSC Physics",
  profession: "",
  bloodGroup: "",
  height: "5 फूट 3 इंच",
  Birthplace: "बेल्हा ता. जुन्नर, पुणे",
  Birthtime: "सकाळी 7:23 वा.",
  location: "मु.पो. बेल्हा ता. जुन्नर, पुणे",
  image: "images/JF11146-face.jpeg",
  Fathername: "श्री. अशोक बाबाजी नेतेवकर",
  Fatheroccupation: "",
  Mothername: "सौ. सुनिता अशोक नेतेवकर",
  Motheroccupation: "",
  Siblings: "भाऊ - विकास अशोक नेतेवकर (विवाहित)",
  Relatives: "ओर, भोसले, गाडे, कुंभार, कदम, अडे, गोरडे, धोत्रे, औटी, घोडके, खेडेकर, कुंभार, हुले, गिराटे, आग्रे, शिंदे",
  expectations: ""
}
,{
  code: "JF11147",
  name: "कु. वैष्णवी प्रमोद कोरे",
  age: "27",
  dateOfBirth: "07/06/1998",
  caste: "हिंदू - मराठा",
  ras: "मिथुन",
  गण: "मनुष्य",
  नाडी: "आद्य",
  देवक: "वासनकुळ",
  education: "M.Com (Banking and Finance)",
  profession: "Link Group, Vikhroli West",
  bloodGroup: "A+",
  height: "5 फूट",
  Birthplace: "शिरूर, ता. जुन्नर, जि. पुणे",
  Birthtime: "",
  location: "विख्रोली (प.), मुंबई",
  image: "images/JF11147-face.jpeg",
  Fathername: "श्री. प्रमोद बाळाजी कोरे",
  Fatheroccupation: "गव्हर्नमेंट & बँकिंग सेवा (निवृत्त)",
  Mothername: "सौ. वर्षा प्रमोद कोरे",
  Motheroccupation: "गृहिणी",
  Siblings: "भाऊ - गणेश प्रमोद कोरे (विवाहित)",
  Relatives: "काळे, लोखंडे, सुकाळे, बोंडके, बोर, बोरुळे, कारंडे, डुंडे, देडे, गाडे",
  expectations: ""
},
{
  code: "JF11148",
  name: "प्राजक्ता बाळासाहेब फाफळे",
  age: "27",
  dateOfBirth: "14/06/1999",
  caste: "हिंदू - मराठा",
  ras: "तुळ",
  गण: "देव",
  नाडी: "अंत्य",
  देवक: "कवड",
  education: "B.E (Computer)",
  profession: "Software Engineer (Cybage)",
  bloodGroup: "A+",
  height: "5.1 फूट",
  Birthplace: "नारायणगाव",
  Birthtime: "सकाळी 9:30 वा.",
  location: "शुभमंगल सोसायटी, धामणखेल, नारायणगाव, ता. जुन्नर, जि. पुणे",
  image: "images/JF11148-face.jpeg",
  Fathername: "डॉ. बाळासाहेब खंडुजी फाफळे",
  Fatheroccupation: "पशुवैद्यकीय डॉक्टर",
  Mothername: "सुनिता बाळासाहेब फाफळे",
  Motheroccupation: "शिक्षिका",
  Siblings: "भाऊ - शुभम बाळासाहेब फाफळे (अविवाहित)",
  Relatives: "इंडे, शेटे, बेडे, कुलकर्णी, आरटे, कोकाटे, हांडे, बाळुंज, निंबाळे",
  expectations: ""
}
,
{
  code: "JF11149",
  name: "कु. पूनम बाबुराव घाडो",
  age: "27",
  dateOfBirth: "03/12/1998",
  caste: "हिंदू - मराठा",
  ras: "वृषभ",
  गण: "वैश्य",
  नाडी: "अंत्य",
  देवक: "चंद्र - सूर्य",
  education: "BSC MLT",
  profession: "Metropolis Health Care Ltd",
  bloodGroup: "B+",
  height: "5 फूट 3 इंच",
  Birthplace: "",
  Birthtime: "रात्री 11:00",
  location: "रूम नं 50, लक्ष्मी निवास सोसायटी, संजय कोकाटे लेन, घाटकोपर पश्चिम, मुंबई 400084",
  image: "images/poonam_baburao_ghado.jpeg",
  Fathername: "श्री. बाबुराव किसन घाडो",
  Fatheroccupation: "",
  Mothername: "सौ. लता बाबुराव घाडो",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "थोरात, ओटे, चिकणे, फाफळे, नेहेरकर, हांडे, कराडे",
  expectations: ""
}
,
{
  code: "JF11150",
  name: "कु. तेजश्री भाऊसाहेब शेळके",
  age: "26",
  dateOfBirth: "29/07/1999",
  caste: "हिंदू - मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "मोराचे पिस",
  education: "बी.ई. (आय.टी.)",
  profession: "MotifWorks India Pvt.Ltd, Pune (20 LPA)",
  bloodGroup: "B+ve",
  height: "5 फूट 7 इंच",
  Birthplace: "श्रीरामपूर",
  Birthtime: "सकाळी 10:45",
  location: "श्रीरामपूर, जि. अहमदनगर",
  image: "images/JF11150-face.jpeg",
  Fathername: "भाऊसाहेब एकनाथ शेळके",
  Fatheroccupation: "सेवानिवृत्त प्रादेशिक व्यवस्थापक",
  Mothername: "मंगल भाऊसाहेब शेळके",
  Motheroccupation: "गृहिणी",
  Siblings: "",
  Relatives: "कडू, रिठे, वाघ, कासार, देव, ढोरके, पोल, कापसे, अडोळे, झुरळे, पळसाणे",
  expectations: ""
},
{
  code: "JF11151",
  name: "कु. अर्चना रामदास धोत्रे",
  age: "27",
  dateOfBirth: "06/09/1998",
  caste: "हिंदू - मराठा",
  ras: "मकर",
  गण: "",
  नाडी: "अंत्य",
  देवक: "सोडस",
  education: "B.Com",
  profession: "National Co-op Bank",
  bloodGroup: "AB+",
  height: "5 फूट 5 इंच",
  Birthplace: "नारायणगाव",
  Birthtime: "दुपारी 2:30",
  location: "नवी मुंबई",
  image: "images/JF11151-face.jpeg",
  Fathername: "रामदास गणपती धोत्रे",
  Fatheroccupation: "",
  Mothername: "शकुंतला रामदास धोत्रे",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "मोरे, ढोले, लोखंडे, बोचरे, वाघ, नेहेरे, कुटिक",
  expectations: ""
},
{
  code: "JF11152",
  name: "कु. सुप्रिया संजय तानपुरे",
  age: "29",
  dateOfBirth: "03/06/1997",
  caste: "हिंदू - मराठा",
  ras: "मेष",
  गण: "मानव",
  नाडी: "मध्य",
  देवक: "पाचपाळी",
  education: "B.E Computer",
  profession: "Accenture Pvt Ltd",
  bloodGroup: "O+ve",
  height: "5 फूट 4 इंच",
  Birthplace: "ओतूर",
  Birthtime: "सकाळी 8:00",
  location: "जुन्नर, पुणे",
  image: "images/JF11152-face.jpeg",
  Fathername: "संजय देवकराम तानपुरे",
  Fatheroccupation: "",
  Mothername: "पूजा संजय तानपुरे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "शेवाळे, घोरपडे, माळकर, शिंदे, वामन",
  expectations: ""
},
{
  code: "JF11153",
  name: "कविता विनायक जाधव",
  age: "31",
  dateOfBirth: "25/02/1995",
  caste: "हिंदू - मराठा",
  ras: "तुला",
  गण: "राक्षस",
  नाडी: "मध्य",
  देवक: "पाचपाळी",
  education: "M.A., B.Ed",
  profession: "शासकीय सेवेत",
  bloodGroup: "A+ve",
  height: "5 फूट 3 इंच",
  Birthplace: "अहमदनगर",
  Birthtime: "",
  location: "",
  image: "images/JF11153-face.jpeg",
  Fathername: "विनायक जाधव",
  Fatheroccupation: "Service",
  Mothername: "",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "पाटील, जाधव, मगर",
  expectations: ""
},
{
  code: "JF11154",
  name: "दिव्या दिलीप शेळार",
  age: "24",
  dateOfBirth: "27/02/2002",
  caste: "हिंदू - मराठा",
  ras: "मेष",
  गण: "देव",
  नाडी: "आद्य",
  देवक: "पाचपाळी",
  education: "B.E (EXTC)",
  profession: "जॉन्सन कंट्रोल",
  bloodGroup: "O+",
  height: "5 फूट 4 इंच",
  Birthplace: "नारायणगाव",
  Birthtime: "रात्री 11:00",
  location: "कोपरखैरणे, नवी मुंबई",
  image: "images/JF11154-face.jpeg",
  Fathername: "दिलीप दत्तात्रय शेळार",
  Fatheroccupation: "",
  Mothername: "वंदना दिलीप शेळार",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "पडवळ, गाढवे, काकडे, काशी, नोबळे",
  expectations: ""
},
{
  code: "JF11155",
  name: "कु. प्राजक्ता रोहिदास मोरे",
  age: "30",
  dateOfBirth: "31/10/1996",
  caste: "हिंदू - मराठा",
  ras: "कन्या",
  गण: "मनुष्य",
  नाडी: "आद्य",
  देवक: "पाचपाळी",
  education: "B.E EXTC",
  profession: "Accenture Services Private Limited",
  bloodGroup: "A+",
  height: "5 फूट 3 इंच",
  Birthplace: "मुंबई",
  Birthtime: "रात्री 8:30",
  location: "डोंबिवली",
  image: "images/JF11155-face.jpeg",
  Fathername: "रोहिदास गंगाराम मोरे",
  Fatheroccupation: "",
  Mothername: "संगिता रोहिदास मोरे",
  Motheroccupation: "",
  Siblings: "1 बहीण",
  Relatives: "काळे, लवटे, जाधव, कुंभार",
  expectations: ""
},
{
  code: "JF11156",
  name: "शिवांजली मंगेश दुंबरे",
  age: "28",
  dateOfBirth: "29/04/1998",
  caste: "हिंदू - मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "पाचपाळी",
  education: "B.E Mechanical",
  profession: "Avians Innovation Technology",
  bloodGroup: "O+",
  height: "5 फूट 2 इंच",
  Birthplace: "नारायणगाव",
  Birthtime: "सायं. 06:10",
  location: "जुन्नर, पुणे",
  image: "images/JF11156-face.jpeg",
  Fathername: "मंगेश उत्तमराव दुंबरे",
  Fatheroccupation: "",
  Mothername: "मंगल मंगेश दुंबरे",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "वाघळे, गोडसे, धोत्रे, जाधव",
  expectations: "पुण्यात नोकरी करणारा मुलगा"
},
{
  code: "JF11157",
  name: "सरस्वती अरुण सोलाट",
  age: "26",
  dateOfBirth: "04/01/2000",
  caste: "हिंदू - मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "पाचपाळी",
  education: "M.DES, B.VOC",
  profession: "मुंबई येथे कंपनीत इंटर्न",
  bloodGroup: "B+",
  height: "5 फूट 3 इंच",
  Birthplace: "",
  Birthtime: "दुपारी 12:39",
  location: "मुंबई",
  image: "images/JF11157-face.jpeg",
  Fathername: "अरुण सोलाट",
  Fatheroccupation: "",
  Mothername: "विनिता सोलाट",
  Motheroccupation: "",
  Siblings: "2 बहिणी",
  Relatives: "पारसेकर, जाधव, शिंदे",
  expectations: ""
},
{
  code: "JF11158",
  name: "सोनल सुभाष कोकाटे",
  age: "30",
  dateOfBirth: "04/01/1996",
  caste: "हिंदू - मराठा",
  ras: "वृषभ",
  गण: "देव",
  नाडी: "मध्य",
  देवक: "मोरिताचे कडे",
  education: "M.Com",
  profession: "",
  bloodGroup: "O+",
  height: "5.4",
  Birthplace: "जुन्नर",
  Birthtime: "सकाळी 7:15",
  location: "भांडुप, मुंबई",
  image: "images/JF11158-face.jpeg",
  Fathername: "सुभाष कोकाटे",
  Fatheroccupation: "",
  Mothername: "कविता कोकाटे",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "हाडवळे, मोरे, महाकाल, वाघ",
  expectations: ""
},
{
  code: "JF11159",
  name: "मृणाली रामदास काळे",
  age: "27",
  dateOfBirth: "02/08/1998",
  caste: "हिंदू - मराठा",
  ras: "वृश्चिक",
  गण: "राक्षस",
  नाडी: "अंत्य",
  देवक: "पाचपाळी",
  education: "B.Sc, MBA Healthcare",
  profession: "Lab Technician",
  bloodGroup: "B+",
  height: "5 फूट 5 इंच",
  Birthplace: "ठाणे",
  Birthtime: "सकाळी 5:25",
  location: "बदलापूर",
  image: "images/JF11159-face.jpeg",
  Fathername: "रामदास जयराम काळे",
  Fatheroccupation: "",
  Mothername: "संघमाबाई रामदास काळे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "बोडके, शिंगोटे, पिंगळे, जाधव",
  expectations: ""
},
{
  code: "JF11160",
  name: "कु. आश्विनी मोहन घोडे",
  age: "25",
  dateOfBirth: "18/07/2000",
  caste: "हिंदू मराठा",
  ras: "",
  गण: "देव",
  नाडी: "अंत्य",
  देवक: "पानकुळी",
  education: "B. Pharmacy",
  profession: "Fortrea Scientific Private Ltd., Hinjewadi, Pune",
  bloodGroup: "B+ve",
  height: "5 फूट 3 इंच",
  Birthplace: "घोडेगाव",
  Birthtime: "सकाळी 10:02",
  location: "जुन्नर, पुणे",
  image: "images/JF11160-face.jpeg",
  Fathername: "श्री. मोहन घोडे",
  Fatheroccupation: "किराणा स्टोअर्स व शेती",
  Mothername: "सौ. कांचन मोहन घोडे",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ",
  Relatives: "घोडे, गांगळे, देशमुख, पारखे, माने",
  expectations: ""
},
{
  code: "JF11161",
  name: "कु. तेजश्री विजयकुमार मगर",
  age: "26",
  dateOfBirth: "20/02/1999",
  caste: "हिंदू मराठा",
  ras: "वृश्चिक",
  गण: "राक्षस",
  नाडी: "आद्य",
  देवक: "साळुंकी पंखी",
  education: "M.A. B.Ed.",
  profession: "जलसंपदा विभाग, पुणे",
  bloodGroup: "B+",
  height: "5.1 फूट",
  Birthplace: "केडगाव, अहमदनगर",
  Birthtime: "संध्याकाळी 06:25",
  location: "अहमदनगर",
  image: "images/JF11161-face.jpeg",
  Fathername: "प्रा. विजयकुमार मगर",
  Fatheroccupation: "प्राध्यापक",
  Mothername: "सौ. मीनाक्षी मगर",
  Motheroccupation: "शिक्षिका",
  Siblings: "1 भाऊ",
  Relatives: "जाधव, पवार, शिंदे, मगर",
  expectations: ""
},
{
  code: "JF11162",
  name: "सायली रविंद्र काकडे",
  age: "25",
  dateOfBirth: "08/09/1999",
  caste: "हिंदू मराठा",
  ras: "सिंह",
  गण: "राक्षस",
  नाडी: "अंत्य",
  देवक: "मरिताचे कडे",
  education: "Bachelor of Computer Engineering",
  profession: "Software Developer (10 LPA) Piramal Finance Limited",
  bloodGroup: "A+",
  height: "5 फूट 3 इंच",
  Birthplace: "मंचर",
  Birthtime: "दुपारी 12:00",
  location: "नेरळ, नवी मुंबई",
  image: "images/JF11162-face.jpeg",
  Fathername: "श्री. रविंद्र काकडे",
  Fatheroccupation: "",
  Mothername: "सौ. वैशाली काकडे",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "गावडे, पवार, राठोड, तावरे",
  expectations: ""
},
{
  code: "JF11163",
  name: "कु. ज्योती एकनाथ पिंगळे",
  age: "27",
  dateOfBirth: "29/06/1997",
  caste: "हिंदू मराठा",
  ras: "मेष",
  गण: "देवगण",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "M.Com",
  profession: "Ezo Technologies Pvt Ltd. (Sr. Accountant)",
  bloodGroup: "O+",
  height: "5 फूट",
  Birthplace: "नवी मुंबई",
  Birthtime: "रात्री 11:44",
  location: "कोपरखैरणे, नवी मुंबई",
  image: "images/JF11163-face.jpeg",
  Fathername: "श्री. एकनाथ पिंगळे",
  Fatheroccupation: "",
  Mothername: "सौ. शारदा पिंगळे",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "आडक, पोखरकर, पाटील",
  expectations: ""
},
{
  code: "JF11164",
  name: "अंकिता हरिश्चंद्र जाधव",
  age: "26",
  dateOfBirth: "08/12/1998",
  caste: "हिंदू मराठा",
  ras: "मिथुन",
  गण: "",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "BCA",
  profession: "IDFC FIRST BANK (Associate Manager)",
  bloodGroup: "O+ve",
  height: "5 फूट 3 इंच",
  Birthplace: "मंचर",
  Birthtime: "रात्री 11:50",
  location: "पुणे",
  image: "images/JF11164-face.jpeg",
  Fathername: "श्री. हरिश्चंद्र जाधव",
  Fatheroccupation: "शेती",
  Mothername: "सौ. मीना जाधव",
  Motheroccupation: "गृहिणी",
  Siblings: "1 बहीण",
  Relatives: "भोसले, शिंदे, पवार",
  expectations: "उच्चशिक्षित, नोकरी करणारा मुलगा"
},
{
  code: "JF11165",
  name: "वृषाली नंदकिशोर शिंदे",
  age: "26",
  dateOfBirth: "14/09/1999",
  caste: "मराठा",
  ras: "तुळ",
  गण: "",
  नाडी: "",
  देवक: "",
  education: "B.Sc. Agri",
  profession: "अॅग्रो स्टार कंपनी, पुणे",
  bloodGroup: "",
  height: "5.7",
  Birthplace: "कोपरगाव",
  Birthtime: "रात्री 09:30",
  location: "अहमदनगर",
  image: "images/JF11165-face.jpeg",
  Fathername: "श्री. नंदकिशोर शिंदे",
  Fatheroccupation: "शेती",
  Mothername: "सौ. सोनाली शिंदे",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "गवांडे, पवार, चव्हाण",
  expectations: ""
},
{
  code: "JF11166",
  name: "कु. पूजा बाळू शिंदे",
  age: "27",
  dateOfBirth: "27/03/1999",
  caste: "हिंदू मराठा",
  ras: "कर्क",
  गण: "राक्षस",
  नाडी: "अंत्य",
  देवक: "सावराचे कडे",
  education: "B.E. IT",
  profession: "TCS (System Engineer)",
  bloodGroup: "B-",
  height: "5 फूट 8 इंच",
  Birthplace: "ठाणे",
  Birthtime: "दुपारी 2",
  location: "ठाणे",
  image: "images/JF11166-face.jpeg",
  Fathername: "श्री. बाळू शिंदे",
  Fatheroccupation: "",
  Mothername: "सौ. इंदुमती शिंदे",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ",
  Relatives: "जाधव, कुंटे, शिंदे",
  expectations: ""
},
{
  code: "JF11167",
  name: "डॉ. श्वेता सयाजीराव चिखले",
  age: "26",
  dateOfBirth: "23/04/1999",
  caste: "हिंदू मराठा",
  ras: "मिथुन",
  गण: "मनुष्य",
  नाडी: "",
  देवक: "कडवे खंडोबा",
  education: "BDS, Certified Endodontist",
  profession: "स्वतःचे क्लिनिक (24 लाख वार्षिक)",
  bloodGroup: "B+",
  height: "5 फूट 5 इंच",
  Birthplace: "मांजरवाडी",
  Birthtime: "रात्री 11:30",
  location: "जुन्नर, पुणे",
  image: "images/JF11167-face.jpeg",
  Fathername: "श्री. सयाजीराव चिखले",
  Fatheroccupation: "शिक्षक",
  Mothername: "सौ. सुमन चिखले",
  Motheroccupation: "शिक्षिका",
  Siblings: "2 बहिणी",
  Relatives: "चिखले, पटोळे, शिंदे",
  expectations: "MBBS / MD / IT / BDS"
},
{
  code: "JF11169",
  name: "कु. सुरभी संजय भोर",
  age: "25",
  dateOfBirth: "04/06/2000",
  caste: "मराठा",
  ras: "मिथुन",
  गण: "मनुष्य",
  नाडी: "आद्य",
  देवक: "वासराचे कडे",
  education: "B.Pharm, MBA(HR)",
  profession: "HR Manager",
  bloodGroup: "AB+",
  height: "5 फूट 3 इंच",
  Birthplace: "पिंपळवंडी",
  Birthtime: "सकाळी 9:21",
  location: "पुणे",
  image: "images/JF11169-face.jpeg",
  Fathername: "श्री. संजय भोर",
  Fatheroccupation: "Govt Electrical Contractor",
  Mothername: "सौ. वर्षा भोर",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ",
  Relatives: "भोर, शिंदे, गवांडे",
  expectations: ""
},
{
  code: "JF11170",
  name: "उत्कर्षा धुलिदास वाणी",
  age: "25",
  dateOfBirth: "04/08/1999",
  caste: "हिंदू मराठा",
  ras: "सिंह",
  गण: "मनुष्यगण",
  नाडी: "मध्य",
  देवक: "पाचपळी",
  education: "B.Sc (IT), Engineering Designing",
  profession: "TATA Consultancy Engineering, Airoli",
  bloodGroup: "O+",
  height: "5 फूट 2 इंच",
  Birthplace: "मुंबई",
  Birthtime: "सायंकाळी 6:45",
  location: "मुंबई",
  image: "images/JF11170-face.jpeg",
  Fathername: "श्री. धुलिदास वाणी",
  Fatheroccupation: "",
  Mothername: "सौ. जयमाला वाणी",
  Motheroccupation: "",
  Siblings: "1 बहीण",
  Relatives: "वाणी, शिंदे, पवार",
  expectations: ""
},
{
  code: "JF11171",
  name: "अंकिता महादेव जाधव",
  age: "27",
  dateOfBirth: "29/06/1998",
  caste: "हिंदू मराठा",
  ras: "वृश्चिक",
  गण: "देवगण",
  नाडी: "मध्य",
  देवक: "पान व बेल",
  education: "MBA (Operation Management)",
  profession: "Assistant Professor",
  bloodGroup: "B+",
  height: "5 फूट 4 इंच",
  Birthplace: "मुंबई",
  Birthtime: "रात्री 11:45",
  location: "नवी मुंबई",
  image: "images/JF11171-face.jpeg",
  Fathername: "महादेव जाधव",
  Fatheroccupation: "",
  Mothername: "सुहासिनी जाधव",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "जाधव, शिंदे, गायकवाड",
  expectations: ""
},
{
  code: "JF11172",
  name: "पल्लवी वसंत धुळवळे",
  age: "32",
  dateOfBirth: "14/03/1993",
  caste: "हिंदू मराठा",
  ras: "वृश्चिक",
  गण: "राक्षस",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "B.E Computer",
  profession: "IBM",
  bloodGroup: "B+",
  height: "5 फूट 3 इंच",
  Birthplace: "मुंबई",
  Birthtime: "सकाळी 8:35",
  location: "नवी मुंबई",
  image: "images/JF11172-face.jpeg",
  Fathername: "वसंत धुळवळे",
  Fatheroccupation: "",
  Mothername: "हिराबाई धुळवळे",
  Motheroccupation: "",
  Siblings: "3 बहिणी",
  Relatives: "धुळवळे, नायकोडी",
  expectations: ""
},
{
  code: "JF11173",
  name: "साक्षी सुनील रोकडे",
  age: "23",
  dateOfBirth: "31/09/2002",
  caste: "हिंदू मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "पाचपळी",
  education: "BMM Graphics and Multimedia",
  profession: "TaskUs",
  bloodGroup: "O+",
  height: "5 फूट 3 इंच",
  Birthplace: "नवी मुंबई",
  Birthtime: "6:45 pm",
  location: "नवी मुंबई",
  image: "images/JF11173-face.jpeg",
  Fathername: "सुनील रोकडे",
  Fatheroccupation: "APMC मार्केट",
  Mothername: "सुरेखा रोकडे",
  Motheroccupation: "",
  Siblings: "",
  Relatives: "पोखरकर, पवार, शिंदे",
  expectations: ""
},
{
  code: "JF11174",
  name: "दीपिका पांडुरंग भोर",
  age: "30",
  dateOfBirth: "10/04/1994",
  caste: "हिंदू मराठा",
  ras: "मेष",
  गण: "मनुष्य",
  नाडी: "मध्य",
  देवक: "",
  education: "B.E Civil",
  profession: "Assistant Manager (12 LPA) Prestige Estates, Mumbai",
  bloodGroup: "O+",
  height: "5 फूट 5 इंच",
  Birthplace: "जुन्नर",
  Birthtime: "रात्री 11:45",
  location: "नवी मुंबई",
  image: "images/JF11174-face.jpeg",
  Fathername: "पांडुरंग भोर",
  Fatheroccupation: "शेती",
  Mothername: "शांता भोर",
  Motheroccupation: "गृहिणी",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "भोर, जाधव, शिंदे",
  expectations: ""
},
{
  code: "JF11175",
  name: "कोमल राजाराम फाफळे",
  age: "33",
  dateOfBirth: "08/10/1992",
  caste: "हिंदू मराठा",
  ras: "कुंभ",
  गण: "राक्षस",
  नाडी: "अंत्य",
  देवक: "",
  education: "B.Sc IT",
  profession: "SVN India Pvt Ltd",
  bloodGroup: "B+",
  height: "5 फूट 2 इंच",
  Birthplace: "मुंबई",
  Birthtime: "दुपारी 12:52",
  location: "मुंबई",
  image: "images/JF11175-face.jpeg",
  Fathername: "राजाराम फाफळे",
  Fatheroccupation: "",
  Mothername: "नंदा फाफळे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "हुलवळे, जाधव, पाटील",
  expectations: ""
},
{
  code: "JF11176",
  name: "रोहिणी दिलीप मुढळे",
  age: "33",
  dateOfBirth: "17/09/1992",
  caste: "हिंदू मराठा",
  ras: "वृषभ",
  गण: "राक्षस",
  नाडी: "अंत्य",
  देवक: "वासनसडी",
  education: "MBA Finance",
  profession: "Infosys",
  bloodGroup: "A+",
  height: "5 फूट 4 इंच",
  Birthplace: "",
  Birthtime: "संध्याकाळी 6:30",
  location: "अहमदनगर",
  image: "images/JF11176-face.jpeg",
  Fathername: "दिलीप मुढळे",
  Fatheroccupation: "शेती",
  Mothername: "नंदा मुढळे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 2 बहिणी",
  Relatives: "कुटे, पाटील",
  expectations: ""
},
{
  code: "JF11177",
  name: "प्रतीक्षा बालासाहेब गुंजाळ",
  age: "25",
  dateOfBirth: "26/07/1999",
  caste: "हिंदू मराठा",
  ras: "धनु",
  गण: "राक्षस",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "B.Pharm",
  profession: "Hospital Job",
  bloodGroup: "O+",
  height: "5 फूट 4 इंच",
  Birthplace: "अहमदनगर",
  Birthtime: "सकाळी 9:30",
  location: "जुन्नर",
  image: "images/JF11177-face.jpeg",
  Fathername: "बालासाहेब गुंजाळ",
  Fatheroccupation: "शेती",
  Mothername: "सविता गुंजाळ",
  Motheroccupation: "गृहिणी",
  Siblings: "2 बहिणी",
  Relatives: "विश्वासराव, जाधव",
  expectations: ""
},
{
  code: "JF11178",
  name: "पूर्वा आनंद दुंडे",
  age: "27",
  dateOfBirth: "07/08/1998",
  caste: "हिंदू मराठा",
  ras: "मकर",
  गण: "",
  नाडी: "अंत्य",
  देवक: "पाचपळी",
  education: "BA + Digital Marketing",
  profession: "Manager - Insurance",
  bloodGroup: "O+",
  height: "5 फूट 4 इंच",
  Birthplace: "निगमगाव",
  Birthtime: "दुपारी 3",
  location: "मुंबई",
  image: "images/JF11178-face.jpeg",
  Fathername: "आनंद दुंडे",
  Fatheroccupation: "",
  Mothername: "शिला दुंडे",
  Motheroccupation: "",
  Siblings: "2 बहिणी",
  Relatives: "गरड, कांबळे",
  expectations: ""
},
{
  code: "JF11179",
  name: "अंकिता संजय ढाकले",
  age: "29",
  dateOfBirth: "03/08/1996",
  caste: "हिंदू मराठा",
  ras: "कन्या",
  गण: "देव",
  नाडी: "आद्य",
  देवक: "पाचपळी",
  education: "M.Sc Chemistry",
  profession: "Sr Associate",
  bloodGroup: "AB+",
  height: "5 फूट 2 इंच",
  Birthplace: "जुन्नर",
  Birthtime: "रात्री 10:05",
  location: "पुणे",
  image: "images/JF11179-face.jpeg",
  Fathername: "संजय ढाकले",
  Fatheroccupation: "",
  Mothername: "प्रेरणा ढाकले",
  Motheroccupation: "",
  Siblings: "1 भाऊ",
  Relatives: "जाधव, सुतार",
  expectations: ""
},
{
  code: "JF11180",
  name: "माधवी भाऊसाहेब शेगुळे",
  age: "26",
  dateOfBirth: "19/02/1999",
  caste: "हिंदू मराठा",
  ras: "",
  गण: "",
  नाडी: "",
  देवक: "मोरे",
  education: "B.E Computer",
  profession: "Atos Syntel Pune",
  bloodGroup: "A+",
  height: "5 फूट 4 इंच",
  Birthplace: "श्रीरामपूर",
  Birthtime: "सायंकाळी 7:45",
  location: "अहमदनगर",
  image: "images/JF11180-face.jpeg",
  Fathername: "भाऊसाहेब शेगुळे",
  Fatheroccupation: "शेती",
  Mothername: "मंगला शेगुळे",
  Motheroccupation: "",
  Siblings: "1 भाऊ, 1 बहीण",
  Relatives: "कडू, शिंदे",
  expectations: ""
}
]
